#!/bin/sh
#
# Expand the sd card partition to 100% from unpartitioned space.
#
# Usage: resize-part "/dev/mmcblk0p2" or resize-part "/dev/mmcblk0" "p2"
# or resize-part "/dev/sda" "2"
#
# Copyright 2019-2022 Xilinx Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

if [ "$#" -eq 2 ]; then
        ROOT_DEV=$1
        PART_NUM=$2
        ROOT_PART=$ROOT_DEV$PART_NUM
        if [ ${#PART_NUM} -eq 2 ]; then
                PART_NUM=$(echo -n $PART_NUM | tail -c 1)
        fi
else
        ROOT_PART=$1
        ROOT_DEV=$(echo $ROOT_PART | cut -c 1-12)
        PART_NUM=$(echo -n $ROOT_PART | tail -c 1)
fi

#back up data before extend partition, otherwise data might be lost
do_expand_rootfs() {

    local target=$1
    local root_part=$2
    local part_num=$3

    if [[ `mount | grep ${root_part}` ]]; then
        echo -e "Yes" | parted ${target} ---pretend-input-tty resizepart ${part_num} 100%
    else 
        parted ${target} resizepart ${part_num} 100%
    fi
}

do_check_media() {

    if ! ls "$ROOT_PART" 2> /dev/null; then
	echo "$ROOT_PART is not an valid SD card partition, please check"
	exit 0
    fi

    do_expand_rootfs $ROOT_DEV $ROOT_PART $PART_NUM
}

if [ "$EUID" -ne 0 ]; then
    echo "Note: Run as sudo or root user"
    exit
fi

if [ "$#" -eq 0 ]; then
    echo "Pass the SD card partition as argument to expand"
else
    do_check_media && resize2fs $ROOT_PART
fi
