#!/bin/sh

type="$1"

[ -z "$type" -a -f "/etc/default/reboot" ] &&
       type=`cat /etc/default/reboot`
[ -z "$type" ] &&
       type=system

case $type in
	apu|APU)	scope=subsystem; type=APU    ;;
	ps|PS)		scope=ps_only; type=PS     ;;
	sys*|SYS*)	scope=system; type=SYSTEM ;;
	*)		echo "Invalid reboot type $type"; exit 1 ;;
esac

echo $type > /etc/default/reboot
echo $scope > /sys/firmware/zynqmp/shutdown_scope
echo "Linux reboot target set to: $type ($scope)"
