#ifndef XGEMM_CONFIG_H
#define XGEMM_CONFIG_H

#define NUM_HW_COLS		50
#define MAT_SIZE		500
#define NUM_COLS		MAT_SIZE
#define NUM_ROWS		MAT_SIZE
#define WIN_SIZE		MAT_SIZE
#define NUM_ELMNTS		(NUM_ROWS * NUM_COLS)
#define NUM_A_ELMNTS_PER_TILE	(NUM_ELMNTS / NUM_HW_COLS)

#endif
