INHERIT += "own-mirrors"
SOURCE_MIRROR_URL ?= "https://petalinux.xilinx.com/sswreleases/rel-v${XILINX_VER_MAIN}/downloads"

# QT code repository is often unavailable (503 or similar)
# Typically specified in meta-qt5/conf/layer.conf
QT_GIT ??= "git://code.qt.io/qt"
QT_MIRROR ?= "git://github.com/qt"
MIRRORS:append = " ${QT_GIT} ${QT_MIRROR}"
