#!/bin/sh

udhcpc_enabled() {
        return 0
}

run_udhcpc() {
	status=$1
	module=$2
	if [ "$status" = "pre" ] && [ "$module" = "finish" ]; then
		if [ ! -d $ROOTFS_DIR/dev ]; then
			if [ -x $_UDHCPC ]; then
				$_UDHCPC
			fi
		fi
	fi
	return 0
}

_UDHCPC="/sbin/udhcpc"

udhcpc_run() {
	add_module_pre_hook "run_udhcpc"
}
