// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1.0
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
//
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xdata_source_top.h"

extern XData_source_top_Config XData_source_top_ConfigTable[];

XData_source_top_Config *XData_source_top_LookupConfig(u16 DeviceId) {
    XData_source_top_Config *ConfigPtr = NULL;

    int Index;

    for (Index = 0; Index < XPAR_XDATA_SOURCE_TOP_NUM_INSTANCES; Index++) {
        if (XData_source_top_ConfigTable[Index].DeviceId == DeviceId) {
            ConfigPtr = &XData_source_top_ConfigTable[Index];
            break;
        }
    }

    return ConfigPtr;
}

int XData_source_top_Initialize(XData_source_top *InstancePtr, u16 DeviceId) {
    XData_source_top_Config *ConfigPtr;

    Xil_AssertNonvoid(InstancePtr != NULL);

    ConfigPtr = XData_source_top_LookupConfig(DeviceId);
    if (ConfigPtr == NULL) {
        InstancePtr->IsReady = 0;
        return (XST_DEVICE_NOT_FOUND);
    }

    return XData_source_top_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif
