// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1.0
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
//
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xmonitor.h"

extern XMonitor_Config XMonitor_ConfigTable[];

XMonitor_Config *XMonitor_LookupConfig(u16 DeviceId) {
	XMonitor_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XMONITOR_NUM_INSTANCES; Index++) {
		if (XMonitor_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XMonitor_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XMonitor_Initialize(XMonitor *InstancePtr, u16 DeviceId) {
	XMonitor_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XMonitor_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XMonitor_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif
