// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1.0
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
//
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xstats_top.h"

extern XStats_top_Config XStats_top_ConfigTable[];

XStats_top_Config *XStats_top_LookupConfig(u16 DeviceId) {
	XStats_top_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XSTATS_TOP_NUM_INSTANCES; Index++) {
		if (XStats_top_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XStats_top_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XStats_top_Initialize(XStats_top *InstancePtr, u16 DeviceId) {
	XStats_top_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XStats_top_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XStats_top_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif
